### PR TITLE
Install Skip

### PR DESCRIPTION
**Pull request by Antsthebul**
I also had to add version.py  to the honesty package, and set version attribute to type int. This is my 1st contrib so i hope i did ok lol. Thanks!

### CODE REVIEW

**Comment by thatch** [comment]
The fix I had in mind was a localized one, near https://github.com/python-packaging/pessimist/blob/main/pessimist/manager.py#L218

Basically it constructs `buf` to be able to run `pip`, but if `item.versions` was empty, the command line would be invalid.  We still want to run the test as normal, just without attempting to install the deps using lines 218-235.

When running the manual test as something like

```
$ pessimist /tmp/example -c true
```

it should output `OK max`; I think your change prevents it from actually testing.

**Comment by Antsthebul** [comment]
I got it to skip the install. now just need to have it still run tests. I removed the hack in cli.py and made it local, I think ill be able to have it working tonight.And will commit when its all completed

**Comment by thatch** [comment]
Make sure you push to your branch again; I don't see changes vs yesterday's state yet.  Good luck!

**Comment by Antsthebul** [comment]
So at least we now have test functionality also, finishes w/  "ok status". Not entirely too sure about the make test but at least we know its there ha.

**Comment by Antsthebul** [comment]
Any feedback? I looked into makfefileS so now i understand it a bit more. It appears one needs to exists first in the brand new directory. So i at least coded for that to be made but then removed. Was the attempt to really make [anything]? I can edit the code to recieve any arg but essentially what it would do would be create a .PHONY  target and replace it with the actual module the user wants to use...Either way, Thanks for letting me contribute

**Comment by thatch** [comment]
The part near `NoInstall` is on the right track, but that can be a simple `if` statement -- you don't need exceptions for that logic.

The rest of it, especially the removal of types and added end-of-line whitespace doesn't seem like it has a purpose.  If some of the other code was intended to make testing easier, you can probably just pass `-c true` or so; a Makefile isn't required, it's just the default.

**Comment by thatch** [comment]
I fixed this with a flag in https://github.com/python-packaging/pessimist/commit/b9cfb1ea1fbfdc5aa419bcae8d9203dfae523305

**Pull request closed without merging**
